#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep time sleep);

use strict;

my $hostname = `hostname`;
chomp $hostname;

my $port = "/dev/cu.usbserial-A100DDXN";
if($hostname eq 'lennyvm')
{
    $port = '/dev/ttyUSB0';
}
    
    
my $port = Device::SerialPort->new($port);
$port->databits(8);
$port->baudrate(500000);
#$port->baudrate(1152000);
#$port->baudrate(1152000);
$port->handshake("xoff");
$port->parity("none");
$port->stopbits(1);
 
my $z = 0;
my $z1 = 0;

my @pixbuf;
foreach my $i (0..2303)
{
    $pixbuf[$i]=0;
}



while(1)
{
	$z+= ((1-sin($z1))/90);
	$z1+=0.10105;
warn $z1;
	$port->write(chr(103));
	my $time1 = time;
 

	my $pixel = 0;
	my $mod = 0;


	
	foreach my $y (0..71)
	{
		foreach my $x (0..31)
		{

			my $num =  sin($x/4+sin($z*3)*9) + sin($z1*sin($x/3)*0.14) + sin($z1*2)
			
			+ sin(($y+$z1)/6+sin($z*10)*3);


			$num = int(abs $num*9)%32;
		
			if($num > 15)
			{
				$num = 31-$num;
			}

			$num=1 if $num<1;

			$pixel++;
			$pixbuf[($y*8+($x%8)+((($x-$x%8)/8) * 576))]=$num;
			
		}
	}

	my $pixel = 0;
	foreach my $mod (1..36)
	{
		my $str;
		foreach my $pix (1..32)
		{
			$str.=chr($pixbuf[$pixel]+$pixbuf[$pixel+1]*16);
			$pixel++;
			$pixel++;
		}
		$port->write(&esc($str));
	}

#	usleep(17000);

	warn 1 / (time - $time1);
}

$port->close();



sub esc($)
{
    my $data = shift;
    
    
    $data =~ s/\x65/\x65\x3/go;
	$data =~ s/\x67/\x65\x1/go;
	$data =~ s/\x68/\x65\x2/go;
	$data =~ s/\x66/\x65\x4/go;
                                                            
	return $data;
}

