#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep time);

use strict;

my $hostname = `hostname`;
chomp $hostname;

my $port = "/dev/cu.usbserial-A2002QDi";
if($hostname eq 'lennyvm')
{
    $port = '/dev/ttyUSB0';
}
    
    
my $port = Device::SerialPort->new($port);
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);
 
my $z = 0;

while(1)
{
	$z+=0.010;
	$port->write(chr(35));
	my $time1 = time;
 

	for my $x (0..287)
	{
		my $str;
		for my $y (0..7)
		{
	
			my $num = abs sin($x*3+4*cos($z))*40*sin($z*2);
			$num += abs sin($y*3-3*cos($z/2))*30 + cos($y*3-sin($z*3))*25;
#			$num += sin($z);	
		
			$num = int($num)%32;
		
			if($num > 15)
			{
				$num = 32-$num;
			}

			$num=1 if $num==0;
			$str.=chr($num);
#			$str.=chr(1);
		}
		$port->write(esc($str));
	
	}

	usleep(10000);

	warn 1 / (time - $time1);
}

$port->close();

sub esc($)
{
    my $data = shift;
    
	$data =~ s/e/\x65\x3/go;
	$data =~ s/\x23/\x65\x1/go;
	$data =~ s/B/\x65\x2/go;
	$data =~ s/f/\x65\x4/go;
                    
	return $data;
}
                        