#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep time sleep);

use strict;

my $hostname = `hostname`;
chomp $hostname;

my $port = "/dev/cu.usbserial-A2002QDi";
if($hostname eq 'ernie')
{
    $port = '/dev/ttyUSB1';
}
    
    
my $port = Device::SerialPort->new($port);
$port->databits(8);
$port->baudrate(500000);
#$port->baudrate(1152000);
#$port->baudrate(1152000);
$port->handshake("xoff");
$port->parity("none");
$port->stopbits(1);
 
my $z = 0;
my $z1 = 0;

my $pixbuf;
#foreach my $i (0..2303)
#{
#    $pixbuf[$i]=0;
#}

my $sleeptime = 21500;

my $z2=0;
my $z3=0;
my $z4=0;

my $frame=0;

my %xpos1;
my %xycache;


my %frame_cache;

while(1)
{
	$z2+=.25;
	$z2 =0 if $z2 == 76;
	my $time1 = time;
 

	my $pixel = 0;
	my $mod = 0;




	
	if(! exists $frame_cache{$z2})
	{
	
	my $zfac = sin($z2/6);
	my $z1fac = sin($z2/12);


#	warn $zfac.' '.$z2;

	foreach my $x (0..31)
	{
		
		my $xfac = $z1fac*sin($x/8);
		
		foreach my $y (0..71)
		{
			my $num = $xfac + sin($y/3) * sin($zfac);

			$num = int $num*16+16;

		
			if($num > 15)
			{
				$num = 31-$num;
			}
			$num=1 if $num<1;
			


			$pixbuf->{$y}{$x}=$num;
			
		}
	}


	my $str;

	my $x = 0;
	my $y = 0;
	my $mod_row=0;
	foreach my $i (0..1151)
	{
		$str.=chr($pixbuf->{$x}{$y+$mod_row}+$pixbuf->{$x}{$y+$mod_row+1}*16);

		$y+=2;
		
		if($y == 8)
		{
			$x++;
			$y=0;
			if($x==72)
			{
				$x=0;
				$mod_row+=8;
			}
		}
	}
		$frame_cache{$z2}=esc($str);
#		warn "prerender frame $z2";
	}
	{
		$port->write(chr(103));
		$port->write($frame_cache{$z2});

	usleep($sleeptime) if $sleeptime > 0;

	my $fps = 1 / (time - $time1);

	$frame++;
	if($frame == 40)
	{
		warn "$fps $sleeptime";
		$frame=0;
	}
	
	$sleeptime+=100 if$fps > 40;
	$sleeptime-=100 if$fps < 40;

	}

}

$port->close();



sub esc($)
{
    my $data = shift;
    
    
    $data =~ s/\x65/\x65\x3/go;
	$data =~ s/\x67/\x65\x1/go;
	$data =~ s/\x68/\x65\x2/go;
	$data =~ s/\x66/\x65\x4/go;
                                                            
	return $data;
}


