#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep time) ;

my $port = Device::SerialPort->new("/dev/ttyUSB0");
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);


my $g =0;
my $j  =7;
while(1)
{
#	my $return=$port->write(chr(66).chr(00).chr(00).chr(0).chr(0).chr(229));
#	sleep(1);
#	my $return=$port->write(chr(66).chr(00).chr(00).chr(0).chr(0).chr(255));
#warn $port->read(1);
	 my $time1 = time;
                         
	foreach my $x (0..7)
	{
		foreach my $y (0..7)
		{
#			warn $g;
			my $c = $g;
			$c = 15-$c if $g > 7;
			my $return=$port->write(chr(66).chr($y).chr($x).chr(($j)));
#			my $return=$port->write(chr(66).chr($y).chr($x).chr(($x*$y/8)));
			$port->read(1);
			usleep(100);
		}
	}
	$g++;
	$g = 0 if $g==16;
#	sleep(1);
    my $now = (time-$time1)/1000000;

	warn 1 / (time - $time1);
	
	
	if($j==0)
	{
		$j=7;
	}
	else
	{
		$j=0;
	}
}
			close($port);
