#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/ttyUSB0");
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);


			my $return=$port->write(chr(66).chr(7).chr(7).chr(7));
			$port->read(1);
$port->close();