#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/ttyUSB0");
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);


			my $return=$port->write(chr(0x42).chr(0).chr(0).chr(1));
			my $return=$port->write(chr(0x42).chr(0).chr(1).chr(2));
			my $return=$port->write(chr(0x42).chr(0).chr(2).chr(3));
			my $return=$port->write(chr(0x42).chr(0).chr(3).chr(4));
			my $return=$port->write(chr(0x42).chr(0).chr(4).chr(5));
			my $return=$port->write(chr(0x42).chr(0).chr(5).chr(6));
			my $return=$port->write(chr(0x42).chr(0).chr(6).chr(7));
			my $return=$port->write(chr(0x42).chr(0).chr(7).chr(8));
			my $return=$port->write(chr(0x42).chr(1).chr(7).chr(9));
			my $return=$port->write(chr(0x42).chr(2).chr(7).chr(10));
			my $return=$port->write(chr(0x42).chr(3).chr(7).chr(11));
			my $return=$port->write(chr(0x42).chr(4).chr(7).chr(12));
			my $return=$port->write(chr(0x42).chr(5).chr(7).chr(13));
			my $return=$port->write(chr(0x42).chr(6).chr(7).chr(14));
			my $return=$port->write(chr(0x42).chr(7).chr(7).chr(15));
			$port->read(1);
$port->close();