#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/ttyUSB0");
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);


my $g =0;
while(1)
{
#	my $return=$port->write(chr(66).chr(00).chr(00).chr(0).chr(0).chr(229));
#	sleep(1);
#	my $return=$port->write(chr(66).chr(00).chr(00).chr(0).chr(0).chr(255));
#warn $port->read(1);

	foreach my $x (0..7)
	{
		foreach my $y (0..7)
		{
			my $return=$port->write(chr(66).chr($y).chr($x).chr($g));
			$port->read(1);
			usleep(500);
		}
	}
	$g++;
	$g = 0 if $g==8;
#	sleep(1);
}
			close($port);
