#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep time);

use strict;

my $hostname = `hostname`;
chomp $hostname;

my $port = "/dev/cu.usbserial-A100DDXG";
if($hostname eq 'ernie')
{
    $port = '/dev/ttyUSB0';
}
    
    
my $port = Device::SerialPort->new($port);
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);
 
while(1)
{
	my $time1 = time;
	my @steps = (0,15);
#	my @steps = (5,5,6,7,8,9,10,11,12,13,13,14,14,14,15,15,15,15,14,14,14,13,13,12,11,10,9,8,7,6,5,5,4,4,4);
	foreach my $col (@steps)
	{
		$port->write(chr(0x23));
		for(0..17)
		{
			$port->write(esc(chr($col*16+$col) x 64));
			usleep(1500);
		}
	}
	warn (1 / (time - $time1)*scalar(@steps));
}

$port->close();

sub esc($)
{
    my $data = shift;
    
    
    $data =~ s/\x65/\x65\x3/go;
	$data =~ s/\x23/\x65\x1/go;
	$data =~ s/\x42/\x65\x2/go;
	$data =~ s/\x66/\x65\x4/go;
                                                            
	return $data;
}

