#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep time);

use strict;

my $hostname = `hostname`;
chomp $hostname;

my $port = "/dev/cu.usbserial-A2002QDi";
if($hostname eq 'lennyvm')
{
    $port = '/dev/ttyUSB0';
}
    
    
my $port = Device::SerialPort->new($port);
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);
 
my $z = 0;

while(1)
{
	my $time1 = time;
foreach my $col (0,15)
#foreach my $col (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1)
{
#	for(0..10)
	{
	$port->write(chr(103));
	for(0..17)
	{
		$port->write(chr($col) x 64);
		$port->write(chr($col) x 64);
		usleep(1500);
	}
#	$port->write(chr(0));
#	usleep(7000);
	}


}
	warn (1 / (time - $time1)*2);
}

$port->close();

                        